export default {
    'success' : {
        'SignupSuccess' : 'please check your email - we have sent a confirmation link',
        'ForgotPassword' : 'A reset link is sent to the email',
        'EventAddedSuccussful' : 'Event added successfully',
        'proposalAdded': 'Proposal added successfully',
        'verificationEmailSent' : 'We have sent an email with a confirmation link to your email address'
    },
    'errors' : {
        'fullname' : 'Please enter valid full name',
        'email' : 'Please enter valid email',
        'phone' : 'Please enter valid phone no',
        'password' : 'Please enter a valid password with min 8 alphanumeric chars.',
        'cpassword' : 'Password does not match',
        'role' : 'Please select a role',
        'emailLogin' : 'Enter email address',
        'passwordLogin' : 'Enter password',
        'NoUid' : 'No UID found.',
        'emailNotVerified' : 'Email address is not verified, click on Resend to resend verification email again',
        'commandKeysMissing' : 'Command keys are missing'
    },
    'auth' : {
        'Login' : 'Login',
        'SignUp' : 'Sign Up',
        'Logout' : 'Logout',
        'MyProfile' :'My Profile',
        'MyAccount' :'My Account',
        'FullName' : 'Full Name',
        'EmailAddress' : 'Email Address',
        'Phone' : 'Phone',
        'Password' : 'Password',
        'ConfirmPassword' : 'Confirm Password',
        'AlreadyHaveAC' : 'Already have an account?',
        'SignIn' : 'Sign In',
        'DontHaveAc' : "Don't have an account?",
        'ForgotPassword' : 'Forgot Password?',
        'VendorLogin' : 'Vendor Login',
        'CoupleLogin' : 'Couple Login',
        'LogoutContent' : 'Are you sure want to logout?',
        'SelectYouRole' : 'Select Your Role',
        'Couple' : 'Couple',
        'Guest' : 'Guest',
        'Vendor' : 'Vendor',
        'ForgotLinkMessage' : 'A reset link will be sent to this email'
    },
    'header' : {
        'Planning' : 'Planning',
        'LocalVendors' : 'Local Vendors',
        'WeddingWebsites' : 'Wedding Websites',
        'Invitations' : 'Invitations',
        'RingsPlDresses' : 'Rings + Dresses'
    },
    'landing' : {
        'WeddingPlanner' : 'Wedding Planner',
        'Wedding' : 'Wedding',
        'Planner' : 'Planner',
        'DreamComeTrue' : 'Your Dream Come True',
        'WeddingPlanninDecor' : 'Wedding planning and decor',
        'WPDContent' : 'Lorem ipsum dolor sit amet, con ctetur adipiscing elit. Donec pha etra mi vestibulum sapien lacinia non tincidunt augue congue eget Vivamus sit amet neque fringilla vestibulum ultrices eget a eros.',
        'WeddingVision' : 'Wedding Vision',
        'WeddingVisionMessage' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'GuestList' : 'Guest List',
        'GuestListMessage' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'Budget' : 'Budget',
        'BudgetMessage' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'Checklist' : 'Checklist',
        'ChecklistMessage' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'VendorManager' : 'Vendor Manager',
        'VendorManagerMessage' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'WedingWebsite' : 'Weding Website',
        'WedingWebsiteMessage' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',

        'LetsPlanHeading':"Let's Plan Your Perfect Wedding",
        'LetsPlanMessage1':"Lorem ipsum dolor sit ametest",
        'LetsPlanMessage2':"Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.",
        'LetsPlanMessage3':"Cras turpis augue, elementum pellentesque porttitor suscipit, consequat ac neque. Nullam condimentum tellus a tortor gravida lacinia. Aliquam finibus augue vitae posuere mattis.",

        'IdeasNTips' : 'Ideas and Tips',
        'IdeasNTipsMssg' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'PlanningBasics' : 'Planning Basics',
        'FamilyNFriends' : 'Family & Friends',
        'WeddingTheme' : 'Wedding Theme',
        'WeddingFashion' : 'Wedding Fashion',
        'WeddingReception' : 'Wedding Reception',
        'WeddingServices' : 'Wedding Services',

        'EasyFindBestWS' : 'Easily find the best wedding services',
        'WeddingVendors' : 'Wedding Vendors',
        'WeddingVendorInfo' : 'Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.',
        'Photography' : 'Photography',
        'BeautyNHealth' : 'Beauty & Health',
        'Catering' : 'Catering',
        'Videography' : 'Videography',
        'Invitation' : 'Invitation',

        'PlanWeddingH1' : 'Plan Any Wedding From Anywhere,',
        'PlanWeddingH2' : 'With Wedding Blizz App'
    },
    'footer' : {
        'CopyRight' : '© 2020 Wedding Blizz. All Rights Reserved',
        'Links' : 'Links',
        'SocialMedia' : 'Social Media',
        'ContactUs' : 'Contact Us',
        'Planning' : 'Planning',
        'LocalVendors' : 'Local Vendors',
        'WeddingWebsite' : 'Wedding Website',
        'Invitations' : 'Invitations',
        'RingsNDresses' : 'Rings + Dresses',
        'AboutUs' : 'About Us',
        'Contact' : 'Contact',
        'CovidTerms' : 'Our COVID-19 Policy',
        'TnC' :'Terms & Conditions',
        'PnP' : 'Privacy Policy',
        'Facebook' :'Facebook', 
        'Instagram' : 'Instagram', 
        'LinkedIn' : 'LinkedIn', 
        'Twitter':'Twitter', 
        'YouTube' : 'YouTube',
        'FooterEmail' : 'info@weddingblizz.com',
        'FooterPhone' : '123 456 7890',
        'FooterAddrss' : '63, Adekunle Fajuyi, Ikeja, Lagos, Nigeria 542684'
    },
    'vendors':{
        'MeetWeddingTeam' : 'Meet Your Wedding Vendor Team',
        'SelectCategory' : 'Select Category',
        'SelectCountry' : 'Select Country',
        'SelectCity' : 'Select City',

        'TopVenCategory' : 'Top Wedding Vendor Categories',
        'ReceptionVenue' : 'Reception Venue',
        'WeddingPhotographers' : 'Wedding Photographers',
        'Videographers' : 'Videographers',
        'BridalSalons' : 'Bridal Salons',
        'Beauty' : 'Beauty',
        'DJs' : 'DJs',
        'WedingBands' : 'Wending Bands',
        'WeddingPlanners' : 'Wedding Planners',
        'WeddingCakes' : 'Wedding Cakes',

        'FindingaVendorH': 'Finding a Wedding Vendor',
        'FindingaVendorSubH': 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',
        'StartYourStyle' : 'Start with Your Style',
        'StartYourStyleInfo' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit. Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. ',
        'UnderstandOptions' : 'Understand the Options',
        'UnderstandOptionsInfo' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit. Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. ',
        'StartConversation' : 'Start Conversation',
        'StartConversationInfo' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit. Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. ',

        'AllVendorCategories' : 'All Wedding Vendor Categories',
        'AllVendorCategoriesSub' : 'Lorem ipsum dolor sit ametest conse ctetur adipiscing elit.',

        'Venue' : 'Venue',
        'Catering' : 'Catering',
        'Photography' : 'Photography',
        'Invitation' : 'Invitation',
        'WeddingGifts' : 'Wedding Gifts',
        'Transportation' : 'Transportation',

        'WeddingVendorsState' : 'Wedding Vendors by State',
        'AbiaWeddings' : 'Abia Weddings'
    },
    'about' : {
        'AboutCompany' : 'About Company',
        'ProvidesWeddingServices' : 'Provides wedding services',
        'ProvidesWeddingServicesS1' : 'Lorem ipsum dolor sit amet.',
        'ProvidesWeddingServicesS2' : 'Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.',
        'ProvidesWeddingServicesS3' : 'Cras turpis augue, elementum pellentesque porttitor suscipit, consequat ac neque. Nullam condimentum tellus a tortor gravida lacinia. Aliquam finibus augue vitae posuere mattis.',
        'ProvidesWeddingServicesS3' : 'Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id.',
        'TotalUsers' : 'Total Users',
        'TotalVendors' : 'Total Vendors',
        'TotalReviews' : 'Total Reviews',

        'PlannBookWedding' : 'Plan And Book Your Wedding',
        'PlannBookWeddingS1' : 'Lorem ipsum dolor sit amet.',
        'PlannBookWeddingS2' : 'Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.',
        'PlannBookWeddingS3' : 'Cras turpis augue, elementum pellentesque porttitor suscipit, consequat ac neque. Nullam condimentum tellus a tortor gravida lacinia. Aliquam finibus augue vitae posuere mattis.',
        'PlannBookWeddingS3' : 'Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id.',
        'Attention2Detail' : 'Attention to Detail',
        'Attention2DetailS1' : 'Lorem ipsum dolor sit amet.',
        'Attention2DetailS2' : 'Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.',
        'InvestorRelations' : 'Investor Relations',
        'InvestorRelationsS1' : 'Lorem ipsum dolor sit amet.',
        'InvestorRelationsS2' : 'Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.',
        'AmazingValue' : 'Amazing Value',
        'AmazingValueS1' : 'Lorem ipsum dolor sit amet.',
        'AmazingValueS2' : 'Donec phar etra mi vestibulum sapien lacinia, non tincidunt augue congue. Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id. Curabitur eget ante dui.',
        'AmazingValueS3' : 'Vivamus sit amet neque fringilla nisi vestibulum ultrices eget a eros. Aenean bibendum justo leo, nec dapibus ipsum vulputate id.',

    },
    'events' : {
        'WeddingEvent' : 'Wedding Event',
        'VendorDetail' : 'Vendor Detail',
        'VendorName' : 'Vendor Name',
        'AddUrWeddingEvent' : 'Add your Wedding Event',
        'NewWeddingEvent' : 'New Wedding Event',
        'SpouseName' : 'Spouse Name',
        'WeddingDate' : 'Wedding Date',
        'WeddingLocation' : 'Wedding Location',
        'GuestCount' : 'Guest Count',
        'EventType' : 'Event Type',
        'WeddingFunction' : 'Wedding Function',
        'WeddingFunction' : 'Wedding Function',
        'WeddingTheme' : 'Wedding Theme',
        'CoupleName' : 'Couple Name',
        'EventDate' : 'Event Date',
        'Vendors' : 'Vendors',
        'Guests' : 'Guests',
        'Guest' : 'Guest',
        'Gifts' : 'Gifts',
        'TheEventFairy' : 'The Event Fairy',
        'VendingServicesOffered' : 'Vending Services Offered',
        'PrefContactMethod' : 'Preferred Contact Method'
    },
    'guest':{
        'AddNGuest' : 'Add New Guest',
        'GuestName' : 'Guest Name',
        'SelectGroup' : 'Select Group',
        'GuestList' : 'Guest List',
        'AddNGroup' : 'Add New Group',
        'AddGuestList' : 'Add Guest List'
        
    },
    'gift':{
        'GiftList' : 'Gift List',
        'AddGift' : 'Add Gift',
        'GiftDetails' : 'Gift Details',
        'Giftedby' : 'Gifted by',
        'AddNewGift' : 'Add New Gift',
        'GiftTitle' : 'Gift Title'
    },
    'account' :{
        'AccountSettings' : 'Account Settings',
        'PersonalDetails' : 'Personal Details',
        'WeddingDetails' : 'Wedding Details',
        'AccountManagement' : 'Account Management',
        'EmailPreferences' : 'Email Preferences',
        'BusinessInformation' : 'Business Information',
        'WeddingDetails' : 'Wedding Details',
        'EditEmail' : 'Edit Email',
        'UpdateYourPassword' : 'Update Your Password',
        'CurrentPassword' : 'Current Password',
        'NewPassword' : 'New Password',
        'ConfirmNewPassword' : 'Confirm New Password',
        'DeleteYourAccount' : 'Delete Your Account',
        'BusinessName' : 'Business Name',
        
    },
    'privacy' : {
        'PrivacyPolicy' : 'Privacy Policy',
        'PrivacyPolicyH':'Lorem ipsum sit dolor sit amet, consetetur sadipscing elitr',
        'PrivacyPolicyC' : 'Consetetur sadipscing elitr, sed diam nons umy eirmod tempor invidunt ut labore set dolore magna aliquyam erat, sed diameset voluptua. At vero eos et jus tortduo dolores et ea rebumtet clita kasd gubergren. Eea takimata sanctus est Lorem ipsum sit dolor sit amet, consetetur sadipscing elitr, sed diam nonu my eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accu ert sam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata erdt sanctus est. Consetetur sadipscing elitr, sed diam nons umy eirmod tempor invidunt ut labore set dolore magna aliquyam erat, sed diameset voluptua. At vero eos et jus tortduo dolores et ea rebumtet clita kasd gubergren. Eea takimata sanctus est Lorem ipsum sit dolor sit amet, consetetur sadipscing elitr, sed diam nonu my eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accu ert sam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata erdt sanctus est.',
        
    },
    'common' : {
        'Search' : 'Search',
        'ViewAll' : 'View All',
        'City' : 'City',
        'State' : 'State',
        'Country' : 'Country',
        'Zipcode':'Zipcode',
        'PhoneNumber' : 'Phone Number',
        'EmailAddress' : 'Email Address',
        'Email' : 'Email',
        'Address' : 'Address',
        'Private' : 'Private',
        'Public' : 'Public',
        'Traditional' : 'Traditional',
        'Family' : 'Family',
        'Images' : 'Images',
        'Image' : 'Image',
        'Browse' : 'Browse',
        'Submit' : 'Submit',
        'Cancel' : 'Cancel',
        'Map' : 'Map',
        'outOf' : 'out of',
        'ViewDetails' : 'View Details',
        'Quantity' : 'Quantity',
        'Description' : 'Description',
        'DeliveryAddress' : 'Delivery Address',
        'FirstName' : 'First Name',
        'LastName' : 'Last Name',
        'Phone' : 'Phone',
        'Update' : 'Update',
        'Delete' : 'Delete',
        'Photos' : 'Photos',
        'Discussions' : 'Discussions',
        'Events' : 'Events',
        'Home' : 'Home',
        'Category' : 'Category',
        'notFoundN' : '404',
        'notFoundT' : 'The Page you are looking for does not exist.',
        'NoRecordFound' : 'No Record Found',
        'Rating' : 'Rating',
        'Chat' : 'Chat',
        'GetAQuote' : 'Get a Quote',
        'Name' : 'Name',
        'Message' : 'Message',
        'Resend' : 'Resend'
    },
    'notifications':{
            'NewProposal':'New Proposal',
            'ProposalBody' : 'You have a new Proposal by'
    }
}